'use client';

import { useEffect, useState } from 'react';
import { useParams, notFound } from 'next/navigation'; // Use notFound from next/navigation
import { getProductByHandle } from '@/lib/shopify'; // Changed from mock-data
import type { Product, Variant } from '@/lib/types';
import { ProductImageGallery } from '@/components/products/product-image-gallery';
import { ProductVariantSelector } from '@/components/products/product-variant-selector';
import { AddToCartButton } from '@/components/products/add-to-cart-button';
import { Separator } from '@/components/ui/separator';
import { Badge } from '@/components/ui/badge';
import { Skeleton } from '@/components/ui/skeleton';
import Link from 'next/link';
import { Button } from '@/components/ui/button';

// Metadata would ideally be generated by a generateMetadata function if this could be a server component
// or if fetching logic was moved to a parent server component.
// For client components, document.title can be set in useEffect.

export default function ProductPage() {
  const params = useParams();
  const productSlug = typeof params.productId === 'string' ? params.productId : ''; // productId is the slug
  
  const [product, setProduct] = useState<Product | null>(null);
  const [selectedVariant, setSelectedVariant] = useState<Variant | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (productSlug) {
      setIsLoading(true);
      getProductByHandle(productSlug)
        .then(fetchedProduct => {
          if (fetchedProduct) {
            setProduct(fetchedProduct);
            if (fetchedProduct.variants && fetchedProduct.variants.length > 0) {
              setSelectedVariant(fetchedProduct.variants.find(v => v.availableForSale) || fetchedProduct.variants[0]);
            } else {
              setSelectedVariant(null); // No variants available
            }
            document.title = `${fetchedProduct.name} - Shopify Headless Express`;
          } else {
            setError('Product not found.'); // Set error for notFound to pick up
          }
        })
        .catch(err => {
          console.error("Failed to fetch product:", err);
          setError('Failed to load product details.');
        })
        .finally(() => {
          setIsLoading(false);
        });
    } else {
      setIsLoading(false);
      setError('Product ID missing.'); // Should not happen with valid routing
    }
  }, [productSlug]);

  useEffect(() => {
    if (error === 'Product not found.') {
      notFound(); // Trigger Next.js 404 page
    }
  }, [error]);


  if (isLoading) {
    return (
      <div className="page-width py-8">
        <div className="grid md:grid-cols-2 gap-8 lg:gap-12">
          <div>
            <Skeleton className="aspect-square w-full rounded-lg" />
            <div className="mt-4 grid grid-cols-4 gap-2">
              {[...Array(4)].map((_, i) => <Skeleton key={i} className="aspect-square w-full rounded-md" />)}
            </div>
          </div>
          <div className="space-y-6">
            <Skeleton className="h-10 w-3/4" />
            <Skeleton className="h-6 w-1/4" />
            <Skeleton className="h-20 w-full" />
            <Skeleton className="h-10 w-1/2" />
            <Skeleton className="h-12 w-full" />
          </div>
        </div>
      </div>
    );
  }

  if (error && error !== 'Product not found.') { // 'Product not found' handled by notFound()
    return (
      <div className="page-width py-12 text-center">
        <h1 className="text-2xl font-semibold text-destructive">{error}</h1>
        <p className="text-muted-foreground mt-2">
          Please try again later or contact support.
        </p>
         <Button asChild className="mt-6">
          <Link href="/shop">Go to Shop</Link>
        </Button>
      </div>
    );
  }
  
  if (!product) { 
    // This case should be covered by isLoading or error state leading to notFound()
    // but as a fallback:
    return (
        <div className="page-width py-12 text-center">
          <h1 className="text-2xl font-semibold">Product not available</h1>
           <Button asChild className="mt-6">
            <Link href="/shop">Go to Shop</Link>
          </Button>
        </div>
      );
  }
  
  if (product.variants.length === 0 || !selectedVariant) {
     return (
        <div className="page-width py-12 text-center">
          <h1 className="text-2xl font-semibold">{product.name}</h1>
          <p className="text-muted-foreground mt-2">
            This product currently has no purchaseable options available.
          </p>
           <Button asChild className="mt-6">
            <Link href="/shop">Go to Shop</Link>
          </Button>
        </div>
      );
  }

  return (
    <div className="page-width py-8">
      <div className="grid md:grid-cols-2 gap-8 lg:gap-12 items-start">
        <ProductImageGallery images={product.images} productName={product.name} />
        <div className="space-y-6 py-4">
          <h1 className="text-3xl lg:text-4xl font-bold tracking-tight">{product.name}</h1>
          
          <p className="text-2xl lg:text-3xl font-semibold text-primary">
            ${selectedVariant.price.toFixed(2)}
          </p>

          <Separator />

          {product.description && (
            <div 
              className="prose prose-sm text-muted-foreground max-w-none" 
              dangerouslySetInnerHTML={{ __html: product.description }} 
            />
          )}


          {product.tags && product.tags.length > 0 && (
            <div className="flex flex-wrap gap-2">
              {product.tags.map(tag => (
                <Badge key={tag} variant="secondary">{tag}</Badge>
              ))}
            </div>
          )}

          <Separator />
          
          <ProductVariantSelector
            variants={product.variants}
            selectedVariant={selectedVariant}
            onVariantChange={setSelectedVariant}
          />
          
          <AddToCartButton 
            product={product} 
            selectedVariant={selectedVariant}
            className="w-full text-lg py-6"
            size="lg"
            disabled={!selectedVariant.availableForSale || selectedVariant.stock <= 0}
          >
            {(!selectedVariant.availableForSale || selectedVariant.stock <= 0) ? 'Out of Stock' : 'Add to Cart'}
          </AddToCartButton>
        </div>
      </div>
    </div>
  );
}

